//export class Pedido {
export interface Pedido {
  uid?: string;
  cantidadmaterial?: number;
  clientedir?: string;
  codeBlock?: string;
  codigodematerial?: string;
  companyblk?: string;
  companycod?: string;
  companydir?: string;
  condiciondepago?: string;
  creado?: Date;
  creadopor?: string;
  descripcionmaterial?: string;
  descuentoporc?: number;
  descuentovalor?: number;
  email?: string;
  fdespacho?: Date;
  fechapedido?: Date;
  fentrega?: Date;
  ffactura?: Date;
  fpago?: Date;
  fpreparacion?:Date;
  ftentrega?: Date;
  idcliente?: string;
  idpedido?: number; //
  idvendedor?: string;
  indicadorImpuestodesc?: string;
  indicadorImpuestoporc?: number;
  lastaction?: string;
  listaprecio?: string;
  modificado?: Date;
  modificadopor?: string;
  motivorechazo?: string;
  nombrealmacenista?:string;
  nomcliente?: string;
  nomvendedor?: string;
  nrobultos?:number;
  nrofactura?: string;
  observacion?: string;
  pdfb64?: string;
  pdfname?: string;
  pdfurl?: string;
  platform?: string;
  precioasociado?: string;
  preciomaterial?: number;
  status?: string;
  ticketurl?: string;
  tipodoc?: string;
  totalCnt?: number;
  totalmontobruto?: number;
  totalmontodescuento?: number;
  totalmontoimpuesto?: number;
  totalmontoneto?: number;
  totalPed?: number;
  totalpormaterial?: number;
  totalPri?: number;
  transporte?: string;
  unidaddemedida?: string;
  /* idpedido?: number; //
  fechapedido?: Date;
  idcliente?: string;
  nomcliente?: string;
  idvendedor?: string;
  nomvendedor?: string;
  listaprecio?: string;
  condiciondepago?: string;
  email?: string;
  codigodematerial?: string;
  descripcionmaterial?: string;
  cantidadmaterial?: number;
  unidaddemedida?: string;
  preciomaterial?: number;
  totalpormaterial?: number;
  creado?: Date;
  creadopor?: string;
  modificado?: Date;
  modificadopor?: string;
  descuentoporc?: number;
  descuentovalor?: number;
  totalmontobruto?: number;
  totalmontodescuento?: number;
  totalmontoimpuesto?: number;
  totalmontoneto?: number;
  precioasociado?: string;
  totalPri?: number;
  totalCnt?: number;
  totalPed?: number;
  indicadorImpuestodesc?: string;
  indicadorImpuestoporc?: number;
  motivorechazo?: string;
  platform?: string;
  ffactura?: Date;
  nrofactura?: string;
  fpreparacion?:Date; //Fecha de preparacion en el almacen
  nombrealmacenista?:string;
  nrobultos?:number;
  fdespacho?: Date;
  ftentrega?: Date;
  fentrega?: Date;
  fpago?: Date;
  tipodoc?: string;
  codeBlock?: string;
  companycod?: string;
  companyblk?: string;
  companydir?: string;
  clientedir?: string;
  pdfurl?: string;
  ticketurl?: string;
  observacion?: string;
  pdfname?: string;
  pdfb64?: string;
  lastaction?: string;
  transporte?: string;
  status?: string; */
}
