//export class Pedido {
export interface Pedido {
  uid?: string;
  cantidadmaterial?: number;
  clientedir?: string;
  codeBlock?: string;
  codigodematerial?: string;
  companyblk?: string;
  companycod?: string;
  companydir?: string;
  condiciondepago?: string;
  creado?: Date;
  creadopor?: string;
  descripcionmaterial?: string;
  descuentoporc?: number;
  descuentovalor?: number;
  diasRetraso?: number;
  email?: string;
  fdespacho?: Date;
  fechapedido?: Date;
  fentrega?: Date;
  ffactura?: Date;
  fpago?: Date;
  fpreparacion?:Date;
  ftentrega?: Date;
  fvencida? : boolean;
  idcliente?: string;
  idpedido?: number;
  idvendedor?: string;
  indicadorImpuestodesc?  :string;
  indicadorImpuestoporc?  :number;
  lastaction?             :string;
  listaprecio?            :string;
  modificado?             :Date;
  modificadopor?          :string;
  montodepago?            :number; //Monto pagado (cobros)
  montopendiente?         :number;
  motivorechazo?          :string;
  nombrealmacenista?      :string;
  nomcliente?             :string;
  nomvendedor?            :string;
  nrobultos?              :number;
  nrofactura?: string;
  observacion?: string;
  pagopuntual?            :boolean; //Indica si el pedido se pagó de forma puntual o no
  porcentaje?: number;
  pdfb64?: string;
  pdfname?: string;
  pdfurl?: string;
  platform?: string;
  precioasociado?: string;
  preciomaterial?: number;
  status?: string;
  statuscobro?    : string;
  ticketurl?: string;
  tipodoc?: string;
  totalCnt?: number;
  totalmontobruto?: number;
  totalmontobrutoBsf?: number;
  totalmontodescuento?: number;
  totalmontoimpuesto?: number;
  totalmontoneto?: number;
  totalPed?: number;
  totalpormaterial?: number;
  totalPri?: number;
  totalPorcentaje?: number;
  totalPorcentajeBsf?: number;
  totalAbonado?: number;
  transporteId?: string;
  transporte?: string;
  compania?: string;
  unidaddemedida?: string;
  modStatus?: any;
  tasaDolar?: number;
}
